export const AN_ACTION = 'AN_ACTION';

export const UPDATE_VENDOR_DETAILS = 'UPDATE_VENDOR_DETAILS';

export const SUBMIT_VENDOR = 'SUBMIT_VENDOR';

export const ADD_ITEM = 'ADD_ITEM';

export const UPDATE_ITEM_DETAILS = 'UPDATE_ITEM_DETAILS';

export const VENDOR_DISPLAY_TOGGLE = 'VENDOR_DISPLAY_TOGGLE';

export const CUSTOMER_DISPLAY_TOGGLE = 'CUSTOMER_DISPLAY_TOGGLE';

export const VENICE_DISPLAY_TOGGLE = 'VENICE_DISPLAY_TOGGLE';

export const SANTA_MONICA_DISPLAY_TOGGLE = 'SANTA_MONICA_DISPLAY_TOGGLE';

export const MARINA_DEL_REY_DISPLAY_TOGGLE = 'MARINA_DEL_REY_DISPLAY_TOGGLE';

export const MAR_VISTA_DISPLAY_TOGGLE = 'MAR_VISTA_DISPLAY_TOGGLE';

export const CULVER_CITY_DISPLAY_TOGGLE = 'CULVER_CITY_DISPLAY_TOGGLE';

export const MARKET_DISPLAY_TOGGLE = 'MARKET_DISPLAY_TOGGLE';

