export const AN_ACTION = 'AN_ACTION';

export const UPDATE_VENDOR_DETAILS = 'UPDATE_VENDOR_DETAILS';

export const SUBMIT_VENDOR = 'SUBMIT_VENDOR';

export const ADD_ITEM = 'ADD_ITEM';

export const UPDATE_ITEM_DETAILS = 'UPDATE_ITEM_DETAILS';