export const AN_ACTION = 'AN_ACTION';

export const UPDATE_VENDOR_DETAILS = 'UPDATE_VENDOR_DETAILS';

export const SUBMIT_VENDOR = 'SUBMIT_VENDOR';

export const ADD_ITEM = 'ADD_ITEM';

export const UPDATE_ITEM_DETAILS = 'UPDATE_ITEM_DETAILS';

export const VENDOR_DISPLAY_TOGGLE = 'VENDOR_DISPLAY_TOGGLE';

export const CUSTOMER_DISPLAY_TOGGLE = 'CUSTOMER_DISPLAY_TOGGLE';

export const MARKET_DISPLAY_TOGGLE = 'MARKET_DISPLAY_TOGGLE';

